apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: decidim-sen-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: decidim-sen-deployment
  minReplicas: 10
  maxReplicas: 40
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
