apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: decidim-sen-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: decidim-sen-deployment
  minReplicas: 6
  maxReplicas: 24
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
