apiVersion: batch/v1
kind: Job
metadata:
  name: decidim-sen-seeds-job
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: decidim-sen-seeds-job
          image: rg.fr-par.scw.cloud/decidim-sen/decidim-sen:latest
          command: ["bundle",  "exec", "rails", "db:seed"]
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: decidim-sen-app-secrets
                key: database_url
          - name : SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: decidim-sen-app-secrets
                key: secret_key_base
          - name: SEED
            value: "true"
      restartPolicy: Never
