apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: decidim-sen-ingress
spec:
  rules:
  - host: petitions.senat.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: decidim-sen-svc
            port:
              number: 80