apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: monitoring
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ingress-nginx
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: cert-manager
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: libre-sh-foundation
  namespace: flux-system
spec:
  interval: 1h
  ref:
    branch: main
  url: https://lab.libreho.st/libre.sh/kubernetes/foundation.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1h
  path: ./monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: libre-sh-foundation
  postBuild:
    substituteFrom:
      - kind: Secret
        name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: loki-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    promtail:
      enabled: true
    loki:
      persistence:
        enabled: true
        size: 100Gi
    config:
      table_manager:
        retention_deletes_enabled: true
        retention_period: 720h
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: default
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: default
spec:
  interval: 24h
  chart:
    spec:
      chart: redis
      version: "17.0.7"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    auth:
      enabled: false
    cluster:
      slaveCount: 3
    securityContext:
      enabled: true
      fsGroup: 2000
      runAsUser: 1000
    volumePermissions:
      enabled: true
    master:
      persistence:
        enabled: true
        path: /data
        size: 8Gi
        storageClass: "scw-bssd-retain"
    slave:
      persistence:
        enabled: true
        path: /data
        size: 8Gi
        storageClass: "scw-bssd-retain"

