
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controller:
      hostPort:
        enabled: true
      ingressClassResource:
        default: true
        enabled: true
      kind: DaemonSet
      service:
        type: LoadBalancer
      config:
        allow-snippet-annotations: "true"
        compute-full-forwarded-for: "true"
        log-format-escape-json: "true"
        log-format-upstream: '{ "remote_addr": "$remote_addr", "request_uri": "$request_uri",
          "args": "$args", "status": "$status", "bytes_sent": "$bytes_sent", "http_referer":
          "$http_referer", "http_user_agent": "$http_user_agent", "http_host": "$http_host",
          "request_time": "$request_time", "content_type": "$sent_http_content_type", "request_method":
          "$request_method", "server_protocol": "$server_protocol", "gzip_ratio": "$gzip_ratio"
          }'
        use-forwarded-headers: "true"
        use-http2: "true"
        use-proxy-protocol: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuerKind: ClusterIssuer
      defaultIssuerGroup: cert-manager.io
