:concurrency: 5
:queues:
  - default
  - mailers
  - newsletter
  - newsletters_opt_in
  - events
  - metrics

:schedule:
  CalculateAllMetrics:
    cron: '0 1 * * *'
    class: CalculateAllMetricsJob
  PreloadOpenData:
    cron: '0 1 * * *'
    class: PreloadOpenDataJob
  CheckPublishedInitiatives:
    cron: '0 1 * * *'
    class: CheckPublishedInitiatives
  CheckValidatingInitiatives:
    cron: '0 1 * * *'
    class: CheckValidatingInitiatives
  NotifyProgressInitiatives:
    cron: '0 1 * * *'
    class: NotifyProgressInitiatives
  CleanSessions:
    cron: '0 1 * * *'
    class: CleanSessions
  CleanAdminLogs:
    cron: "0 9 0 * * *"
    class: Decidim::Cleaner::CleanAdminLogsJob
    queue: scheduled
  CleanInactiveUsers:
    cron: "0 9 0 * * *"
    class: Decidim::Cleaner::CleanInactiveUsersJob
    queue: scheduled
