{
 "title": "Compare Response time",
 "description": "Loki v2+ showcase using JSON NGINX access logs.",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "KPI's",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({app=\"ingress-nginx\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({app=\"ingress-nginx\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "NGINX logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (bytes_over_time({app=\"ingress-nginx\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Realtime visitors ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({app=\"ingress-nginx\"} | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "# NGINX log lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({app=\"ingress-nginx\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Request statistics over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overview of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5,{app=\"ingress-nginx\"} | json | status=200 | request_uri !~ \"/assets/.*\" |  unwrap request_time |  __error__=\"\"  [$__interval]) by (host)\n",
     "legendFormat": "Median"
    },
    {
     "expr": "quantile_over_time(0.95,{app=\"ingress-nginx\"} | json | status=200 | request_uri !~ \"/assets/.*\" | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)\n",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "max by (host) (max_over_time({app=\"ingress-nginx\"} | json | status=200 | request_uri !~ \"/assets/.*\" | unwrap request_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({app=\"ingress-nginx\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}