apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonLabels:
  grafana_datasource: "1"

configMapGenerator:
  - name: grafana-datasources
    files:
      - datasource.yaml
