---
name: Push and deploy to k8s

on:
  push:
    branches:
      - feature/kubernetes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build . --compress --tag ${{ secrets.PRODUCTION_TAG }}
      - name: Login to registry
        run: |
          docker login ${{ secrets.REGISTRY }} -u userdoesnotmatter -p ${{ secrets.TOKEN }}
      - name: Push Image
        run: |
          docker push ${{ secrets.PRODUCTION_TAG }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Apply changes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f kube
      - name: Run rolling update
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment